### ISSUE TITLE
Fails to work when editing code on a remote repository

### ISSUE THREAD

**Issue by Zubbbz** [Goz3rr/vscode-glualint#10]
[Video of the problem](https://youtu.be/l06_dNCCQsk)

**Comment by Goz3rr** [comment]
Thanks for the report, seems like this was caused by the remote repository extension using virtual workspaces. I've published version 0.8.0 which will work with vfs.

Please note that [due to the way the virtual filesystem works](https://code.visualstudio.com/api/extension-guides/virtual-workspaces#language-extensions-and-virtual-workspaces) it's not possible to set the working directory for glualint and thus it will not be able to find any config files in your repo. There is nothing I can do about this. You can either check the repo out fully or put the config file in your home folder.
